In [20]:
import pandas as pd 
import numpy as np

from scipy.sparse import csr_matrix

In [4]:
df = pd.read_csv('Metrics.csv')

In [5]:
df

position  items  times  trial  irts   sizes  intersections  ranks  param  \
0           0      9      1      0     0  5661.0            0.0      0      1   
1           1     12     10      0     9  6428.0          430.0     12      1   
2           2      1     20      0    10  5647.0          426.0      9      1   
3           3     13     30      0    10  6024.0          387.0     10      1   
4           4     10    100      0    70  5794.0          427.0     12      1   
..        ...    ...    ...    ...   ...     ...            ...    ...    ...   
993         2      2     20    197    10  5905.0          484.0     13     97   
994         3     13     50    197    30  5922.0          453.0     12     97   
995         4     14    180    197   130  5642.0          432.0     11     97   
996         0      2      1    198     0  6010.0            0.0      0     98   
997         1      3     10    198     9  6140.0          471.0     13     98   

     num_memories_recalled  
0                        7  
1                        7  
2                        7  
3                        7  
4                        7  
..                     ...  
993                      5  
994                      5  
995                      5  
996                      2  
997                      2  

[998 rows x 10 columns]

In [19]:
df.groupby('times').agg({'num_memories_recalled': 'mean'})

num_memories_recalled
times                       
1                   5.225352
9                   2.000000
10                  5.148810
11                  5.666667
20                  5.282353
...                      ...
930                 6.666667
931                11.000000
940                 7.000000
970                11.000000
980                 5.000000

[125 rows x 1 columns]

In [26]:
data_sparse = np.ones_like(df.trial.values.astype(int))
recalls_bin = csr_matrix(
    (
        data_sparse,
        (
            df.trial.values.astype(int),
            df.times.values.astype(int),
        ),
    )
).toarray()
recalls_bincum = np.cumsum(recalls_bin, axis=1)
print(recalls_bincum)

[[  0   1   0 ...   0   0   0]
 [  0   1   0 ...   0   0   0]
 [  0   1   0 ...   0   0   0]
 ...
 [  0 140   0 ...   0   0   1]
 [  0 141   0 ...   0   0   1]
 [  0 142   0 ...   0   0   1]]


In [27]:
recalls_bincum.shape

(199, 981)